fix: pass I2C address to Adafruit_ADS1115 constructor instead of begin()
begin() takes no arguments; address must be passed to the constructor.

Fixes esp32s3-cdc build:
src/MQ135.cpp: error: no matching function for call to 'Adafruit_ADS1115::begin(uint8_t, TwoWire*)'